name: FCookie
on: push
jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Frontend Checkout
        uses: actions/checkout@v3
      - name: Frontend Test
        run: go test
        working-directory: frontend
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Backend Checkout
        uses: actions/checkout@v3
      - name: Backend Build
        run: docker build .
        working-directory: backend
      - name: Frontend Checkout
        uses: actions/checkout@v3
      - name: Frontend Build
        run: docker build .
        working-directory: frontend
  Run:
    name: Run
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: Backend Checkout
      uses: actions/checkout@v3
    - name: Backend Run
      run: docker run backend:v1.0
      working-directory: backend
    - name: Frontend Checkout
      uses: actions/checkout@v3
    - name: Frontend Run
      run: docker run frontend:v1.0
      working-directory: frontend