name: FCookie
on: push
jobs:
  Clone-down:
    name: Clone Down Repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo

  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Backend Build
        run: go build backend/.

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Frontend
        uses: go test
        with:
          path: frontend