name: FCookie
on: push
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Frontend Test
      - uses: actions/checkout@v3
        run: go test
        working-directory: frontend