name: FCookie
on: push
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Frontend Checkout
        uses: actions/checkout@v3
      - name: Frontend Test
        run: go test
        working-directory: frontend